#pragma config(Sensor, dgtl1,  solenoid,       sensorDigitalOut)
#pragma config(Sensor, dgtl2,  quad,           sensorQuadEncoder)
#pragma config(Motor,  port2,           drive1,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           drive2,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           steer,         tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port5,           drive3,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           drive4,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//------Variables---------------------------------------------------------------------------------------
const short leftButton = 1;
const short centerButton = 2;
const short rightButton = 4;
int gear = 1;
int gear1Speed;
int screenMenu = 4;						//1: Gear and Speed |2: Battery |3: Manual |4: Auto |5: Drag Race|6: High Load|
int screenStart = 1;
int speed;
int temp = 0;
int gearThreshold;
int batteryLevel;
int dragStart = 0;
//------Functions---------------------------------------------------------------------------------------

void manualMode() {
	clearTimer(T1);
	while(true) {
		batteryLevel = nImmediateBatteryLevel / 90; //Determines Battery Percentage

		if(screenMenu > 1 && (vexRT(Btn5U) == 1 || nLCDButtons==leftButton)) { 						//Controls screen
			screenMenu--;
			screenStart = 1;
		}
		else if(screenMenu < 2 && (vexRT(Btn6U) == 1 || nLCDButtons==rightButton)) {
			screenMenu++;
			screenStart = 1;
		}

		if(time1(T1)>=100) {										//Determines Speed of the robot
			speed = -SensorValue(quad);												//
			clearTimer(T1);																		//
			SensorValue(quad) = 0;														//
		}
		startMotor(drive1, vexRT(Ch3));											//Matches motor speed to joystick
		startMotor(drive2, vexRT(Ch3));											//
		startMotor(steer, vexRT(Ch4) / 3);											//
		startMotor(drive3, vexRT(Ch3));
		startMotor(drive4, vexRT(Ch3));

		if(vexRT(Btn8D)== 1) {															//Checks if button is pressed to change gear
			if(gear == 1) {																		//Checks the gear of the transmission
				SensorValue(solenoid) = 1;											//Extends solenoid to change gear
				gear++;																					//Updates gear variable
			}
			else {
				SensorValue(solenoid) = 0;											//Retracts solenoid to change gear
				gear--;																					//Updates gear variable
			}
			wait(.3);
		}
		if (vexRT(Btn7D) == 1 || nLCDButtons == centerButton) {														//Returns to mode selection
			screenStart = 1;
			screenMenu = 4;
			wait(.3);
			break;
		}
	}
}
//------------------------------------Automatic--------------------------------------------------------

void automaticMode() {
	clearTimer(T1);
	while(true) {
		int batteryPercentage = nImmediateBatteryLevel / 90; //Determines Battery Percentage

		startMotor(drive1, vexRT(Ch3));											//Matches motor speed to joystick
		startMotor(drive2, vexRT(Ch3));											//
		startMotor(steer, vexRT(Ch4) / 3);											//
		startMotor(drive3, vexRT(Ch3));
		startMotor(drive4, vexRT(Ch3));

		if(screenMenu > 1 && (vexRT(Btn5U) == 1 || nLCDButtons==leftButton)) { 						//Controls screen
			screenMenu--;
			screenStart = 1;
		}
		else if(screenMenu < 2 && (vexRT(Btn6U) == 1 || nLCDButtons==rightButton)) {
			screenMenu++;
			screenStart = 1;
		}
		//Determines Speed of the robot
		if(time1(T1)>=100) {																//
			speed = -SensorValue(quad);												//
			clearTimer(T1);																		//
			SensorValue(quad) = 0;														//
		}
		if(speed >= 110 && gear == 1) {
			SensorValue(solenoid) = 1;												//Extends solenoid to change gear
			gear1Speed = 1;
			gear++;
		}
		else if(speed <= 90 && gear == 2) {
			SensorValue(solenoid) = 0;												//Retracts solenoid to change gear
			gear1Speed = 0;
			gear--;

		}
		if (vexRT(Btn7D) == 1 || nLCDButtons == centerButton) {														//Returns to mode selection
			screenStart = 1;
			screenMenu = 4;
			wait(.3);
			break;
		}
	}
}
//------------------------------------Drag Race--------------------------------------------------------

void dragRace() {
	screenMenu = 1;
	while(true) {
		if(vexRT(Btn7D) == 1 || nLCDButtons == centerButton) {
			screenStart = 1;
			screenMenu = 4;
			wait(.3);
			break;
		}
		if(vexRT(Btn8D) == 1) {
			dragStart = 1;
			wait(.3);
		}

		while(dragStart == 1) {
			startMotor(drive1, 127);											//Turns all motor to max speed
			startMotor(drive2, 127);											//
			startMotor(steer, vexRT(Ch4) / 3);						//
			startMotor(drive3, 127);
			startMotor(drive4, 127);

			if(time1(T1)>=100) {																// Monitors robot sped
				speed = -SensorValue(quad);												//
				clearTimer(T1);																		//
				SensorValue(quad) = 0;														//
			}
			if(speed >= 110 && gear == 1) {
				SensorValue(solenoid) = 1;												//Extends solenoid to change gear based on velocity
				gear1Speed = 1;
				gear++;
			}
			else if(speed <= 90 && gear == 2) {
				SensorValue(solenoid) = 0;												//Retracts solenoid to change gear
				gear1Speed = 0;
				gear--;
			}
			if(vexRT(Btn8D) == 1) {
				stopMotor(drive1);
				stopMotor(drive2);
				stopMotor(drive3);
				stopMotor(drive4);
				stopMotor(steer);
				dragStart = 0;
			}
		}
	}
}


//--------------------------------------Tasks----------------------------------------------------------
task digitalReadOut() {																//Controls digital readout
	while(true) {
		//-----Screen 1----------------------------------------------------------------------------------------
		while(screenMenu == 1) {													//Screen 1 Gear and Speed
			if(screenStart == 1) {													//Checks if the screen has just changed menus
				clearLCDLine(0);															//Clears LCD
				clearLCDLine(1);															//
				displayLCDString(0, 0, "Initializing...");							//Writes speed to the display
				screenStart = 0;
			}
			if(gear == 1) {																	//Checks and diplays respective gear
				displayLCDCenteredString(1, "Gear: 1");				//
			}
			else if(gear == 2) {																					//
				displayLCDCenteredString(1, "Gear: 2");				//
			}
			else {
				displayLCDCenteredString(1, "Error");
			}
			clearLCDLine(0);
			displayLCDString(0,2,"Speed:");
			displayLCDNumber(0, 9, speed);
			wait(.2);
		}


		while(screenMenu == 2) {													//Screen 2 battery level
			if(screenStart == 1) {
				clearLCDLine(0);
				clearLCDLine(1);
				displayLCDCenteredString(0,"Battery Level:");
				displayLCDString(1,7,"%");
				screenStart = 0;
			}
			displayLCDNumber(1,8,batteryLevel);
			wait(.2);
		}


		while(screenMenu == 3) {													//Screen 3 Manual
			if(screenStart == 1) {
				clearLCDLine(0);
				clearLCDLine(1);
				displayLCDCenteredString(0,"Mode Select");
				displayLCDCenteredString(1,"   Manual  >");
				screenStart = 0;
			}
			wait(.2);
		}


		while(screenMenu == 4) {													//Screen 4 Automatic
			if(screenStart == 1) {
				clearLCDLine(0);
				clearLCDLine(1);
				displayLCDCenteredString(0,"Mode Select");
				displayLCDCenteredString(1,"<  Automatic  >");
				screenStart = 0;
			}
			wait(.2);
		}


		while(screenMenu == 5) {													//Screen Drag Race
			if(screenStart == 1) {
				clearLCDLine(0);
				clearLCDLine(1);
				displayLCDCenteredString(0,"Mode Select");
				displayLCDCenteredString(1,"<  Drag Race   ");
				screenStart = 0;
			}
			wait(.2);
		}
	}
}

//-----------------------------------------------------------------------------------------
task main() {
	bLCDBacklight = true;
	startTask(digitalReadOut);
	while(true) {
		if(temp == 0) {																		//Makes sure variable is within screen parameters
			screenMenu = 4;
			temp = 1;
		}

		if(screenMenu > 3 && (vexRT(Btn5U) == 1 || nLCDButtons==leftButton)) {				//Checks if user wants to change menu left
			screenStart = 1;
			screenMenu--;
			wait(.3);
		}
		else if(screenMenu < 5 && (vexRT(Btn6U) == 1 || nLCDButtons==rightButton)) {  //right
			screenStart = 1;
			screenMenu++;
			wait(.3);
		}
		if(vexRT(Btn7D) == 1 || nLCDButtons == centerButton) {											//Checks if user has locked in choice
			screenStart = 1;
			wait(.3);
			if(screenMenu == 3) {																											//Initializes manual
				screenMenu = 1;
				temp = 0;
				manualMode();
			}
			else if(screenMenu == 4) {																								//Initializes automatic
				screenMenu = 1;
				temp = 0;
				automaticMode();
			}
			else if(screenMenu == 5) {																								//Initializes drag race
				screenMenu = 1;
				temp = 0;
				dragRace();
			}
		}
	}
}
